safe: false
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue
permalink: /:year/:month/:title.html

paginate: 10
paginate_path: "/blog/page_:num/"

gems:
- jekyll-redirect-from
- jekyll-paginate